### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-generator-csharp#126]
Could you add some usages instructions to the `README` for this repo?

Knowing how to run the generator via Docker would be super useful!

**Comment by shaneqld** [comment]
Have a look at [generateapis.sh](https://github.com/googleapis/google-cloud-dotnet/blob/master/generateapis.sh) in the [google-cloud-dotnet](https://github.com/googleapis/google-cloud-dotnet) repo.  It shows how the libraries are generated.

Note that while this generator (and other Google client generators) imply that they can generate non-Google client libraries, they do so only with effort on your behalf.  You'll need to put in some work to understand how they work, implement or modify authentication logic (which is hard-coded for Google OAuth, hard-coded using `GOOGLE_APPLICATION_CREDENTIALS` environment variable, and implemented in a nested package reference), modify the generated files, etc. Have fun! :)

**Comment by meredithslota** [comment]
Closing out. Please reopen if still needed. :)
