### ISSUE TITLE
More detail in exceptions would be helpful

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#157]
I've just run the generator against a branch of googleapis/googleapis for Spanner Database Admin, and it's failed with:

> System.InvalidOperationException: No resource type with name: '*'

I'm now going to add the details of "what's the name of the message causing this problem?" It would be great if details like that were present in general. Will probably create a PR for this myself.

**Comment by chrisdunelm** [comment]
Yes, a number of the error messages could do with being more detailed.

**Comment by jskeet** [comment]
I'm going to close this issue as it's probably not useful - but any time we run into a generation issue where more details would be useful, let's add the details before we fix the proto.
