### ISSUE TITLE
Support maps in request parameters

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#174]
There may be a subtle reason this isn't supported, but I don't know what that would be.

If we ever want to support Google.Cloud.Container.V1Beta1, we'll need to allow a map field to be in a method signature.

**Comment by chrisdunelm** [comment]
The subtle reason is probably that it hasn't yet been required :)
Yes, I'll implement this soon.

**Comment by jskeet** [comment]
This also stops us from migrating Dataproc... and it looks like it *is* supported in the monolithic generator, which surprised me a bit.
