### ISSUE TITLE
Multiple list-like operations using the same response generates invalid code

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#203]
The [Cloud Talent Jobs Service](https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/job_service.proto) contains these methods:

```proto
rpc SearchJobs(SearchJobsRequest) returns (SearchJobsResponse) { ... }
rpc SearchJobsForAlert(SearchJobsRequest) returns (SearchJobsResponse) { ... }
```

The generator then creates two extra partial classes for `SearchJobsResponse`, making it implement `IPageResponse<MatchingJob>`. The generator should only generate a single partial class here.

**Comment by chrisdunelm** [comment]
Fixed in #204
