### ISSUE TITLE
Generate name for fixed-pattern resource names

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#221]
PubSub has a topic pattern of "_deleted-topic_". Currently that generates an enum value with a blank name, and a field of just `s_`. We should probably take an approach of:

- Split on punctuation
- Remove empty entries
- Apply PascalCase

So this would become `DeletedTopic`.

It's a very rare case, but it would be good not to have to write a patch :)

**Comment by chrisdunelm** [comment]
Fixed in #222
