### ISSUE TITLE
C#: Generate more idiomatic API Exception class for API error handling

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator-csharp#237]
**tl;dr** The current Exception thrown on API Error in the C# GAPIC isn't developer-friendly

### Idiomatic Expectation _(what a developer might **'guess'**)_

```cs
using Google.Cloud.Product.V1;

static void Main() {
  var client = ProductService.Create();
  try {
    client.ApiMethod();
  }
  catch (Google.Cloud.Product.V1.ProductApiException e) { // catch (ProductApiException)
  catch (Google.Cloud.ApiException e) { // or maybe this? // catch (ApiException)
    e.InnerException; // Grpc.Core.RpcException
    e.HelpLink;       // Something. Anything. Not null, please?
    e.Message;        // delegate => .Status.Message ?
    e.StatusCode;     // delegate => .Status.StatusCode ?
    // < However y'all .NET folks would *GUESS* to access the error data >
    // < would be a good starting point for this simplified interface >
  }
}
```

### Current Exception handling in GAPICs

```cs
using Google.Cloud.Product.V1;

static void Main() {
  var client = ProductService.Create();
  try {
    client.ApiMethod();
  }
  catch (Grpc.Core.RpcException e) {
    // Hmm... where can I find a field on RpcException that is relevant to
    // the actual Product API that I am calling?
    Log(e.Status.StatusCode); // Grpc.Code.StatusCode enum. Rly? Srsly?
    Log(e.InnerException);    // d'oh! NULL  > Why does the exception bubble up
    Log(e.HelpLink);          // d'oh! NULL  > all the way from the Transport Layer ??
    Log(e.Message);           // Why does this string look like a serialized object?
    Log(e.Data.Count);        // Nope, empty, nothing useful here.
    Log(e.Trailers.Count);    // Um. What. There are 3 of these, whatever they are 🤷🏼
    Log(e.Status.Detail);     // Ah, yay, this at least has the API error message!
  }
}
```

> Note: some API methods are `void` so the response value (`Empty`) cannot be used to check for error conditions, try/catch is required to handle errors

_**Observe!**_ Me poking around, trying to find relevant info on the gRPC RpcException...

![screen shot 2018-04-12 at 12 45 00 pm](https://user-images.githubusercontent.com/280/38701460-c3b378f4-3e52-11e8-9875-992304b8f470.png)

**Feature request:** provide an idiomatic, easy to use Exception to use for API Errors

**Comment by shaneqld** [comment]
Personally, I really like the fact that there's just RpcException. I really hope this doesn't change.

Whenever I use a gRPC client, I know that I need to catch RpcException. I don't need to look through the docs. I don't need to guess what the exception type is. And the StatusCode is standardized.

The only downside is when you call a gRPC service **within** a gRPC server method handler. If you don't catch RpcException, it will be propagated and potentially exposes internal information. But if you're not catching RpcException, you're doing it wrong.

**Comment by jskeet** [comment]
Closing this issue - this hasn't come up from customers, and I think it's unlikely at this point that we'll change.
