### ISSUE TITLE
Corner case: a field called "types" generates a property called Types_ - test generator needs to know this

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#243]
If a message has a field called `types`, the generated property is `Types_` to avoid conflicting with the nested class `Types` generated when there are nested messages/enums.
The unit test generator doesn't handle this yet, and expects to be able to use a `Types` property.

**Comment by chrisdunelm** [comment]
The client generator will also need to know this. For example in the case where the `Types` field is a resource-name.

**Comment by jskeet** [comment]
Right. Do we already have this *sort* of thing encapsulated? If so, I'm happy to take it on - if it's going to require a redesign, you're probably better placed. (But this isn't urgent.)

**Comment by chrisdunelm** [comment]
It's _probably_ just this `CSharpPropertyName` method that needs updating: https://github.com/googleapis/gapic-generator-csharp/blob/0f6c48651e3c58e19b38e3be7a9d698563d419e4/Google.Api.Generator/ProtoUtils/ProtoExtensions.cs#L76

**Comment by jskeet** [comment]
Fab - will give it a go later, thanks :)
