### ISSUE TITLE
Corner case: if an API with client FooBar defines a FooBarSettings message, we get a conflict

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#244]
(Example: https://github.com/googleapis/googleapis/blob/master/google/cloud/accessapproval/v1/accessapproval.proto)

I can see this one being really fiddly to fix :(

**Comment by chrisdunelm** [comment]
Hmm yes, that's a bit nasty. Both classes are in the same namespace.
We could rename the generated `FooBarSettings` class, but that'll then be a breaking change to add a message of the same name :(

**Comment by jskeet** [comment]
Yup. This is probably something that needs further thought.
(The API isn't urgent, as far as I'm aware.)

**Comment by jskeet** [comment]
This has come up again now I'm trying to generate Access Approval. We probably need to revisit this a little more urgently.

Two non-generator change options:

- Rename the proto message as a pregeneration step
- Rename the service (e.g. to AccessApprovalService) as a pregeneration step

The latter of these is probably the simplest approach, but let's discuss it.

**Comment by jskeet** [comment]
Closing as we can't really make the generator handle this. We'll find the conflict quickly enough, and can then rename either the message or the service appropriately.
