### ISSUE TITLE
Nuget package for library

### ISSUE THREAD

**Issue by unchase** [googleapis/gapic-generator-csharp#252]
Will the library be published as a nuget package?

**Comment by chrisdunelm** [comment]
We expect that this generator will eventually be released as a nuget package; however we have no plans to do so soon.

**Comment by jskeet** [comment]
Given that we now have some other dotnet tools (so we know how to do it), I'm starting to wonder whether this would be worth doing after all. We probably wouldn't use it for Bazel builds, but other scripts could just install the right version. (Note that we'd probably still want to be able to override that to use a local version, so it won't actually streamline the code in the scripts, but it *might* have an impact on generation times.)
