### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/gapic-generator-csharp#268]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by chrisdunelm** [comment]
I've done most of this.
However, it appears that to select status checks there needs to have been a PR merge within the last week, which is not the case in this repo. When the next PR goes in, I'll update the rules.

**Comment by chrisdunelm** [comment]
Done
