### ISSUE TITLE
Bazel rules fail to build on MacOS (Darwin x86_64)

### ISSUE THREAD

**Issue by aohren** [googleapis/gapic-generator-csharp#289]
Attempting to invoke the Bazel rules for GAPIC generation fails on MacOS. Looks like [`csharp_compiler_repo.bzl`](https://github.com/googleapis/gapic-generator-csharp/blob/aa4ed5afbcf2f7557419614596edc0e0a6d0f663/rules_csharp_gapic/csharp_compiler_repo.bzl#L17) is hardcoded to fetch the Linux x64 version of the dotnet compiler, which obviously won't run on anything except Linux x64? 

```
ERROR: An error occurred during the fetch of repository 'gapic_generator_restore':
   Failed to execute command: `/private/var/tmp/_bazel_aohren/755911223d1a3dde461b23447f5a3cf9/external/csharp_compiler/dotnet_compiler/dotnet restore restore/src/Google.Api.Generator/Google.Api.Generator.csproj --packages=restore/packages --verbosity=quiet`
Exit Code: 126
STDERR: /private/var/tmp/_bazel_aohren/755911223d1a3dde461b23447f5a3cf9/external/csharp_compiler/dotnet_compiler/dotnet: /private/var/tmp/_bazel_aohren/755911223d1a3dde461b23447f5a3cf9/external/csharp_compiler/dotnet_compiler/dotnet: cannot execute binary file
```

**Comment by chrisdunelm** [comment]
@aohren You are correct that the rule is currently hardcoded for linux only.
This should be fixed.

**Comment by jskeet** [comment]
Closing as not required.
