### ISSUE TITLE
x-goog-request-params header not generated for streaming calls

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#328]
Spotted in https://github.com/googleapis/google-cloud-dotnet/issues/6310

In [ServiceImplClientClassGenerator](https://github.com/googleapis/gapic-generator-csharp/blob/master/Google.Api.Generator/Generation/ServiceImplClientClassGenerator.cs#L116) we don't generate calls to WithGoogleRequestParam for streaming calls (either bidi or server streaming).

It's slightly surprising that this hasn't caused any problems before, and we should be careful to check that it won't break anything if we *do* start generating it everywhere, but it looks like it would at least be simple to fix if we *do* want to generate that everywhere.

**Comment by viacheslav-rostovtsev** [comment]
ack, very interesting.
I think we do need to generate it everywhere.

**Comment by jskeet** [comment]
Thinking about it more, I'm not sure it makes sense for bidi, given that there can be multiple requests. At least, we don't have a `WithGoogleRequestParam` method on `ApiBidirectionalStreamingCall`.

I'm doing it now for server-streaming...
