### ISSUE TITLE
Incorrect Service name in gapic_metadata.json for Access Approval API

### ISSUE THREAD

**Issue by danoscarmike** [googleapis/gapic-generator-csharp#341]
The service name in `gapic_metadata.json` is not correct. It is currently `AccessApprovalService` but according to the API [proto](https://github.com/googleapis/googleapis/blob/master/google/cloud/accessapproval/v1/accessapproval.proto#L67) it should be simply `AccessApproval`. Similarly per the [API Index](https://github.com/googleapis/googleapis/blob/master/api-index-v1.json):

```
"services": [
        {
          "shortName": "AccessApproval",
          "fullName": "google.cloud.accessapproval.v1.AccessApproval",
          "methods": [
            {
```

**Comment by jskeet** [comment]
This isn't actually an issue in the generator itself - it's an artifact of the way we generate AccessApproval and a couple of other libraries.

Unfortunately, the AccessApproval API has a message called AccessApprovalSettings, which would clash with a class that would be generated. We therefore rename the service to AccessApprovalService in [this shell script](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.AccessApproval.V1/midmicrogeneration.sh), during generation.

We do the same for [Bigtable](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Bigtable.V2/midmicrogeneration.sh) and [PubSub](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.PubSub.V1/midmicrogeneration.sh).

So the metadata is correct for what the generator sees, but that's not the original service name.

The simplest workaround is probably to patch the metadata files after generation... are you happy with that?
